qemu/tests/cpuid: fix "-cpu ?" command
The command being run is a shell command, so running it as "-cpu ?"
without any quotes around "?" will make the shell expand "?" to the list
of filenames with one letter in the current directory. This caused funny
issues during my testing:

  16:05:17 DEBUG| Running '/home/ehabkost/pessoal/proj/virt/qemu/install/bin/qemu-system-x86_64 -cpu ?'
  16:05:17 ERROR| In function (test_qemu_cpu_models_list):
  16:05:17 ERROR| Call from:
    File "/home/ehabkost/pessoal/proj/virt/virt-test/qemu/tests/cpuid.py", line 456, in run_cpuid
      print_exception(tests_group)
  16:05:17 ERROR| Exception from:
  Traceback (most recent call last):
    File "/home/ehabkost/pessoal/proj/virt/virt-test/qemu/tests/cpuid.py", line 36, in __new__
      ret = self.test(*args, **kargs)
    File "/home/ehabkost/pessoal/proj/virt/virt-test/qemu/tests/cpuid.py", line 95, in test
      result = utils.run(cmd)
    File "/usr/lib/python2.7/site-packages/autotest/client/shared/base_utils.py", line 788, in run
      "Command returned non-zero exit status")
  CmdError: Command </home/ehabkost/pessoal/proj/virt/qemu/install/bin/qemu-system-x86_64 -cpu ?> failed, rc=1, Command returned non-zero exit status
  * Command:
      /home/ehabkost/pessoal/proj/virt/qemu/install/bin/qemu-system-x86_64 -cpu
      ?
  Exit status: 1
  Duration: 0.0409200191498

  stderr:
  Unable to find CPU definition: t
  Unable to find x86 CPU definition

The error above happened because I had a file named "t" inside my local tree.

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>